steps:
# Docker Build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/test-project-393906/cicd:$SHORT_SHA', '.']

# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/test-project-393906/cicd:SHORT_SHA']
  
  # Deploying to cloud-Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'test-project-393906', '--allow-unauthenticated', '--region=us-west2', '--platform=managed','--image=gcr.io/test-project-393906/cicd:$SHORT_SHA']
